# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Playwright tests (lesson19)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: ./lesson19
        run: npm ci

      - name: Install browsers
        working-directory: ./lesson19
        run: npx playwright install --with-deps

      - name: Run tests
        working-directory: ./lesson19
        run: npx playwright test --headed=false

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: lesson19/playwright-report
